### ISSUE TITLE
Deprecate in favor of 'undo-fu-session'

### ISSUE THREAD

**Issue by ideasman42** [emacsorphanage/undohist#13]
As this package doesn't seem to be maintained, would it be worth considering it deprecated in favor of undo-fu-session?

https://codeberg.org/ideasman42/emacs-undo-fu-session

It has the following improvements:

- Undo & redo history (the full non-linear state is stored).
- Undo can optionally be linearized (behavior of undo-only).
- Compression for stored undo history.
- Optionally limit the number of files stored by removing older files.

----

Would it be worth linking to undo-fu-session in the readme? (for e.g.)

**Comment by tarsius** [comment]
Since I have used neither package (and have disabled the respective feature in `undo-tree`), I don't know enough to make that decision.

> Would it be worth linking to undo-fu-session in the readme? (for e.g.)

Please open a pull-request for that. (Also link to the other alternatives please.)

**Comment by ideasman42** [comment]
Submitted  #15, linked to undo-tree and undo-fu-session, as far as I know these are the only packages that contain this functionality.

**Comment by tarsius** [comment]
Thanks!
